version: '3'
services:
  
  mongo:
    image: mongo:3.6

  microservice-product:
    build: 
      context: "./microservice-product"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/application 
    expose:
     - 8080
    ports:
     - "8080:3000"
    links:
     - mongo 
    depends_on: 
     - mongo

  microservice-provider:
    build: 
      context: "./microservice-provider"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/application 
    expose:
     - 8081
    ports:
     - "8081:3000"
    links:
     - mongo 
    depends_on: 
     - mongo

  microservice-sale:
    build: 
      context: "./microservice-sale"
    environment:
     - MONGODB_URI=mongodb://mongo:27017/application 
    expose:
     - 8082
    ports:
     - "8082:3000"
    links:
     - mongo 
    depends_on: 
     - mongo

    gateway:
      build:
        context: "./graphql-gatewayapi"
      expose:
     - 80
    ports:
     - "80:3000"
    links:
     - microservice-product
     - microservice-provider
     - microservice-sale
    depends_on: 
     - microservice-product
     - microservice-provider
     - microservice-sale
     